/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: '.',
        'Ext.ux': './extjs/ux/',
        Neton: './extjs/ux/',
        
    }
});

Ext.application({

    requires: [
        'Ext.ux.Router'
    ],
    enableRouter: false,
    views: [
        'ui.LoginPanel',
        'ui.Viewport',
        'ui.DashboardPanel',
        'ui.ChangePassWindow',
        'SampleMenuPanel1',
        'SampleMenuPanel2'
    ],
    autoCreateViewport: true,
    controllers: [
        'ui.LoginController',
        'ui.DashboardController',
        'module.SampleController'
    ],
    name: 'App',

    launch: function() {
        Actions.NetonApp_Security.isLogged({}, function(response){
        if (response === false){
            // mostra a página de login
            this.getController('ui.LoginController').showLoginPanel();
        } else {
            this.setSession(response);
            this.getController('ui.DashboardController').showDashboardPanel(response);

            // registra o código de verificação da sessão aberta
            Ext.TaskManager.start({
                run: this.keepSession,
                interval: 60000
            });	
        }
    },this);
    },

    setSession: function(session) {
        this.session = session;
    },

    getSession: function() {
        return this.session;
    },

    keepSession: function() {
        Actions.NetonApp_Security.isLogged({}, function(response){
        if (response === false){
            Ext.Msg.alert('SESSÃO EXPIRADA','Sua sessão expirou e foi fechada. Efetue login novamente!', function(){
                location.reload();
            });

        }
    },this);
    }

});
