/*
 * File: app/view/ui/ChangePassWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ui.ChangePassWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.changepasswindow',

    width: 298,
    layout: {
        type: 'fit'
    },
    iconCls: 'icon-lock',
    title: 'Troca de Senha',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'form',
                    bodyPadding: 10,
                    fieldDefaults: {
                        labelAlign: 'top',
                        allowBlank: false,
                        msgTarget: 'side',
                        labelClsExtra: 'label-bold',
                        enableKeyEvents: true
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtSenha',
                            fieldLabel: 'Senha atual',
                            name: 'senha',
                            inputType: 'password'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtNovaSenha',
                            fieldLabel: 'Nova senha',
                            name: 'novaSenha',
                            inputType: 'password'
                        },
                        {
                            xtype: 'textfield',
                            initialPassField: 'txtNovaSenha',
                            anchor: '100%',
                            itemId: 'txtConfirmaSenha',
                            fieldLabel: 'Confirme a nova senha',
                            name: 'confirmaSenha',
                            inputType: 'password',
                            vtype: 'password'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'button',
                                            formBind: true,
                                            itemId: 'btnConfirmar',
                                            scale: 'medium',
                                            text: 'Confirmar troca'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCancelar',
                                    text: 'Cancelar'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});