/*
 * File: app/view/ui/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ui.LoginPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.loginpanel',

    frame: true,
    width: 304,
    layout: {
        type: 'fit'
    },
    title: 'Acesso restrito',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    itemId: 'tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'form',
                            height: 161,
                            itemId: 'panelLogin',
                            defaults: {
                                labelAlign: 'top',
                                msgTarget: 'side'
                            },
                            bodyPadding: 15,
                            title: 'Login',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'txtLogin',
                                    fieldLabel: 'Login',
                                    labelClsExtra: 'label-bold',
                                    name: 'login',
                                    allowBlank: false,
                                    enableKeyEvents: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'txtSenha',
                                    fieldLabel: 'Senha',
                                    labelClsExtra: 'label-bold',
                                    name: 'senha',
                                    inputType: 'password',
                                    allowBlank: false,
                                    enableKeyEvents: true
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    itemId: 'btnAcessar',
                                                    margin: '0 5 0 0',
                                                    scale: 'medium',
                                                    text: 'Acessar'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            itemId: 'panelRecuperarSenha',
                            defaults: {
                                labelAlign: 'top',
                                labelClsExtra: 'label-bold',
                                msgTarget: 'side'
                            },
                            bodyPadding: 15,
                            title: 'Recuperar senha',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'txtEmail',
                                    fieldLabel: 'Email',
                                    name: 'email',
                                    allowBlank: false,
                                    enableKeyEvents: true,
                                    vtype: 'email'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'button',
                                            margins: '0 5 0 0',
                                            formBind: true,
                                            itemId: 'btnSolicitarSenha',
                                            scale: 'medium',
                                            text: 'Solicitar a senha'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});