/*
 * File: app/view/ui/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ui.Viewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.uiviewport',

    requires: [
        'App.view.ui.LoginPanel',
        'Neton.window.Flash'
    ],

    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'ctLoading',
                    layout: {
                        align: 'center',
                        pack: 'center',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            cls: 'loading-ct',
                            height: 40,
                            html: 'Verificando sessão...',
                            itemId: 'ctInfo',
                            width: 180
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'panelLogin',
                    layout: {
                        align: 'center',
                        pack: 'center',
                        type: 'vbox'
                    },
                    bodyBorder: false,
                    bodyStyle: 'background-color: transparent !important;',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            cls: 'sys-toolbar',
                            itemId: 'loginToolbar',
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'logo',
                                    height: 50,
                                    itemId: 'ctLogo',
                                    style: {
                                        backgroundColor: '#fff'
                                    },
                                    width: 214
                                },
                                {
                                    xtype: 'tbfill'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 1,
                            itemId: 'ctSeparator',
                            style: 'background-color: #fff;'
                        }
                    ],
                    items: [
                        {
                            xtype: 'loginpanel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});